# Generated by Django 3.2.12 on 2022-05-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20220523_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
